name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Code formatting check
      run: lein cljfmt check
    - name: Code linting
      uses: DeLaGuardo/clojure-lint-action@v1
      with:
        clj-kondo-args: --lint src test
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run tests
      run: lein cloverage --codecov
    - name: Update code coverage report
      run: bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
